config/routes.rb
Rails.application.routes.draw do
  
  root 'application#posts'
  
  get  '/user/(:id)', to: 'application#posts'
  post  '/user/(:id)', to: 'application#posts'
  
  
  
  post '/addpost', to: 'application#addpost'
  get  '/saved/(:id)', to: 'application#saved'
  post  '/saved/(:id)', to: 'application#saved'
  get  '/feed/(:id)', to: 'application#feed'
  post  '/feed/(:id)', to: 'application#feed'
  
  get  '/mail', to: 'application#mail' 
 
    
  resources :users
  match '/signup',  to: 'users#new',            via: 'get'
  resources :sessions, only: [:new, :create, :destroy]
  
   post '/email_enter', to: 'sessions#email_enter'
   
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  
  get '/enter', to: 'sessions#enter'
  post '/enter', to: 'sessions#email_enter'
  
  get '/invest', to: 'invest#viki5'
  
  get ':controller/:action/:id/'
  post ':controller/:action/(:id)/'

    
  

end

app/controllers/invest_controller.rb
class InvestController < ActionController::Base
    include SessionsHelper
    before_action :login
    
    def viki5

    end

end

app/views/invest/_menu.html.erb
 <div style="">

  <a href= '/' class = "menu "  >Блоги</a>
  <a href= '/invest' class = "menu active" >Инвестиции</a>
  <%= link_to "Вход", signin_path ,  class:"exit menu" if @current_user.nil?%>
  <%= link_to "Выход", signout_path, method: "delete" ,  class:"menu" unless @current_user.nil?%>
  
 </div>

app/views/invest/_name.html.erb
<img class="avatar " 
src="<%= 'uploads/viki5.jpg' if @single_user.nil? %>" 
alt="" border="0">


 

  <div class="name_css">
      <h3>Инвестиции</h3>
      
      
       
  </div>
 

app/views/invest/viki5.html.erb
<div class="post">
    
<h3>Книга "Технология успеха viki5"</h3>
     
</div >

<div class="post">
    
<h3>Видео лекция "Технология успеха viki5"</h3>
     
</div >

<div class="post">
    
<h3>Роль инвестора</h3>
   <div class="choise_div" >
   <% if @current_user.choise and @current_user.choise.investor %>
    <a class="choise_menu " href="/api/setchoise/investor">вы выбрали роль инвестора</a>
    <% else%>
   
    <a class="choise_menu " href="/api/setchoise/investor">выбрать роль инвестора</a>
    
    <% end%>
     </div >
     
     


Я готов дать деньги предпринимателям для того чтобы они открыли на мои 
деньги бизнесы и затем отдавали мне
от 50 до 90% чистой прибыли от работы данных бизнесов.<br>


<br>



    
<h3>Роль предпринимателя</h3>
 
 
 <div class="choise_div" >
   <% if @current_user.choise and @current_user.choise.commresant %>
    <a class="choise_menu " href="/api/setchoise/commresant">вы выбрали роль предпринимателя</a>
    <% else%>
   
    <a class="choise_menu " href="/api/setchoise/commresant">выбрать роль предпринимателя</a>
    
    <% end%>
     </div >
     
Я готов взять деньги у инвесторов, открыть на эти деньги бизнес а затем отдавать
инвесторам от 50 до 90% чистой прибыли. <br>
Дайте мне инвестиции. <br>

<br>


     

    <h3>Роль ментора</h3>
 
 <div class="choise_div" >
   <% if @current_user.choise and @current_user.choise.mentor %>
    <a class="choise_menu " href="/api/setchoise/mentor">вы выбрали роль ментора</a>
    <% else%>
   
    <a class="choise_menu " href="/api/setchoise/mentor">выбрать роль ментора</a>
    
    <% end%>
     </div >
     
Я знаю как открыть и развить тот или иной бизнес и 
я готов передать мои знания в обмен на определенный процент от 
чистой прибыли тех бизнесов которые вы откроете по моему плану. <br>

<br>

    
<h3>Роль клиента</h3>
  <div class="choise_div" >
   <% if @current_user.choise and @current_user.choise.customer %>
    <a class="choise_menu " href="/api/setchoise/customer">вы выбрали роль клиента</a>
    <% else%>
   
    <a class="choise_menu " href="/api/setchoise/customer">выбрать роль клиента</a>
    
    <% end%>
     </div >
     
Я не готов инвестировать свои деньги в бизнес, однако я
не хочу чтобы в мире был разрыв между бедными и богатыми, поэтому с удовольствием
воспользуюсь услугами ваших бизнесов в качестве клиента и покупателя. <br>

<br>

</div >